In [7]:
import numpy as np
import pandas as pd

# Vandermonde matrix

In [98]:
a = [1,2,3,4,5]

In [113]:
def vander(a, increasing = False):
    out = []
    a = np.array(a)
    if increasing == False:
        for i in range(len(a)):
            b = a**(5-i-1)
            b = b.tolist()
            out.append(b)
        out = np.array(out)
        return out.T
    
    else:
        for i in range(len(a) - 1 ,-1,-1):
            b = a**(5-i-1)
            b = b.tolist()
            out.append(b)
        out = np.array(out)
        return out.T
        

In [114]:
vander(a, False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [110]:
np.vander([1,2,3,4,5], increasing= False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [115]:
vander(a, True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [116]:
np.vander([1,2,3,4,5], increasing= True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

# Moving Average

In [37]:
def moving_avg(nos, window ):
    out = []
    for i in range(window-1):
        out.append(np.nan)
    for i in range(len(nos)):
        if (i + window) <= len(nos):
            sum = 0
            for j in range(i, i+ window):
                sum = sum + nos[j] 
            out.append(sum/window)
    
    return np.array(out).round(6)
    

In [38]:
moving_avg(nos, 3)

array([      nan,       nan, 47.333333, 44.666667, 48.333333, 54.666667,
       64.      , 65.      , 78.666667, 58.666667, 43.      , 38.      ,
       59.      , 56.333333, 50.333333])

In [36]:
nos = [72, 54, 16, 64, 65, 35, 92, 68, 76, 32, 21, 61, 95, 13, 43]
nos = pd.Series(nos)
nos.rolling(3).mean()

0           NaN
1           NaN
2     47.333333
3     44.666667
4     48.333333
5     54.666667
6     64.000000
7     65.000000
8     78.666667
9     58.666667
10    43.000000
11    38.000000
12    59.000000
13    56.333333
14    50.333333
dtype: float64

In [34]:
np.random.randint(10,100, 15)

array([72, 54, 16, 64, 65, 35, 92, 68, 76, 32, 21, 61, 95, 13, 43])